FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN  pip install --upgrade pip
RUN  python3 -m pip install --upgrade setuptools
RUN  pip install pika redis 

RUN pip install moviepy \
    && pip install google-cloud-container google-cloud-speech

RUN  mkdir /app
COPY	worker-server.py /app

ENV PYTHONUNBUFFERED="True"
ENV PYTHONIOENCODING="UTF-8"

WORKDIR /
CMD	python3 app/worker-server.py
