apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: utsavag/kt-search-worker:v15
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis
          - name : RABBITMQ_HOST
            value: rabbitmq
        volumeMounts:
          - mountPath: "/data/uploads/"
            name: worker-mount
      volumes:
        - name: worker-mount
          persistentVolumeClaim:
            claimName: worker-pvc
---
